### ISSUE TITLE
Good source for awesome application to include

### ISSUE THREAD

**Issue by azzamsa** [CodyReichert/awesome-cl#116]
I think to know which application is awesome, is to look at 

- [Monthly Quicklisp download stats ](http://blog.quicklisp.org/2017/08/july-2017-quicklisp-download-stats.html)
- ASD files of CL prject. see what library they use. (but I think the first point already enough)

**Comment by vindarel** [comment]
yes it is a great way to discover the ecosystem. Again no need and no use to include everything. For example cl-fad is super-downloaded but AFAIU it is superseeded by uiop, included in asdf. We had a discussion and removed puri from the list because it has basically no website and no documentation, and two other libraries are good.
