### ISSUE TITLE
notabug repo is outdated

### ISSUE THREAD

**Issue by cage2** [CodyReichert/awesome-cl#193]
Hello,

seems to me that the repo on notabug is not in sync with the one here.

Also the fact that you can submit PR and issues both here and there may generate confusion.

Hope this helps.
Bye.
C.

**Comment by CodyReichert** [comment]
Hey @cage2 	- thanks for checking out the notabug version! You're right, it's hard to keep them in sync right now because I just use a different `git origin` and forget the notabug one:/

Do they have a "mirror" option, or is there some way to set that up? I'll definitely look into it - we want both updated.

**Comment by cage2** [comment]
On Fri, Sep 28, 2018 at 12:03:48AM -0700, Cody Reichert wrote:

> Hey @cage2  -

Hi! :)

> thanks  for checking out  the notabug  version!

Thank to you for spreading the Common Lisp awesomeness :)

> You're
> right, it's hard to keep them in sync right now because I just use a
> different `git origin` and forget the notabug one:/

> Do they have a "mirror" option, or is there some way to set that up?
> I'll definitely look into it - we want both updated.

IIRC they  have a "new  migration" option,  then you should  check the
"this repository  will be a mirror"  checkbox. But i am  just guessing
here because never actually  set up a mirror. I think  this is worth a
try.

Thank you again!
Bye.
C.

**Comment by cage2** [comment]
On Wed, Nov 07, 2018 at 08:17:50AM -0800, Cody Reichert wrote:
> Closed #193 via #208.

Great! Thank you! :)

C.
