### ISSUE TITLE
Should we visually mark de-facto libraries ?

### ISSUE THREAD

**Issue by vindarel** [CodyReichert/awesome-cl#196]
Good idea from this discussion https://www.reddit.com/r/lisp/comments/9iq8dc/what_happened_to_the_common_lisp_foundation/

> Perhaps there should be a way to visually mark popular things on a list so it's obvious that e.g. bordeaux-threads is on top of a list because it's so widely used, not just because it's first alphabetically. It would also make which categories need revisiting more obvious.

I suggest a simple 👍 (https://unicode-table.com/en/1F44D/ ) before the library name:

- 👍 ASDF - Another System Definition Facility; a build system for Common Lisp. Expat.

(If it's too ugly, maybe *community standard*:

- ASDF - Another System Definition Facility; a build system for Common Lisp. Expat. *community standard*.
)

But, we have to stress in the contributing guidelines (see the new pending PR) that our goal is *not* to list every defacto/popular libraries.
When there is a "conflict", it would be useful to name the most popular lib anyway, if only to show that this section was curated. We could do like I did with Dexador:

-   Dexador - An HTTP client, that aims at replacing Drakma. MIT.

citing Drakma on the same line, afterwards.

**Comment by CodyReichert** [comment]
@vindarel 	- very interesting, sorry for the slow reply just getting back in town!

I'm not _opposed_, especially if it's agreed that will overall help new users, but I do have a thought on that. I like the fact that right now we do two things:

1. we promote a community standard by putting it first
2. We also support other, _awesome_, projects that are worth checking out.

I do not want to detract attention from the other awesome projects too much. Is it enough to know/document that they're ordered this way, and that the list is actively maintained?

Let me know what you think. It's obviously hard to make sure _all_ of the projects are beginner-friendly, and I think you have a much better view of what's currently good for the community :)

**Comment by vindarel** [comment]
> Is it enough to know/document that they're ordered this way, and that the list is actively maintained?

It seems it isn't enough, because each section doesn't have a community standard, and some sections still lack editing ("implementations" and possibly others: graphics ? GUI ? Game dev ?)

> I do not want to detract attention from the other awesome projects too much. 

I see, right. 

What about: if we already promote a library by marking it "community standard", it isn't compulsory to put it first. For example, I'd really promote Spinneret over cl-who. Would marking cl-who standard make many more newcomers try it first and have a bad experience ? If you think so, either we don't do this, either we stay very flexible :]

**Comment by CodyReichert** [comment]
> It seems it isn't enough, because each section doesn't have a community standard

That's a really really good point that I didn't think of before. With that perspective, I think it makes a lot more sense - you're right.

> if we already promote a library by marking it "community standard", it isn't compulsory to put it first. For example, I'd really promote Spinneret over cl-who

I also absolutely agree here, and even on this specific case -- eg, I would want to promote cl-who _and_ spinneret. So yeah, thinking over this a bit more I think it's a great idea. Especially with regards to the first point, it should be way more clear which library to at least start with.

---

One last thought: what about instead of a fist we use a :star:.

Additionally, what we could do for cases like cl-who and spinneret is something like this:
- :star2: cl-who (<-- community standard star)
- :star: spinneret (<-- endorsed by maintainers of this repo)

That way there's a clear -- _we_ like spinneret and cl-who is a community de-facto.

Do you think two types of stars like that would be too much?

Either way I'm definitely down for any sort of indication on the community standards - thanks again for your thoughts on that!

**Comment by vindarel** [comment]
Ok cool, I'll make a PR and we'll refine the notation and rules with specific cases !

Good idea for the two signs (though the two stars may be too similar).

**Comment by vindarel** [comment]
First pass: https://github.com/vindarel/awesome-cl/tree/community-standards

**Comment by CodyReichert** [comment]
:heart_eyes: Oh this is great!

Actually, that turned out way better than I expected. Sections like, especially:

![image](https://user-images.githubusercontent.com/7034627/47442230-a12d9800-d777-11e8-9ccc-1fda772b4196.png)

:+1: That is really good, this is going to be a big help reading through the list.

If you want to push it to a PR I can help review, fix up any typos, and go through any other sections!
