### ISSUE TITLE
Drakma?

### ISSUE THREAD

**Issue by mdbergmann** [CodyReichert/awesome-cl#485]
Just a question.
I don't see Drakma HTTP client. Should it not be there at least as an alternative to Dexador?
Actually I still use it.
Or is Dex so much better?

**Comment by vindarel** [comment]
I don't think it is necessary to list Drakma, since

- Dexador cites it at the top of its readme
- Dexador seems to be working well, to be a no-brainer
- we don't need to list all libraries here (that's for Cliki)

but I never used Drakma and I don't know if it has advantages, with more feedback we'll could add it if justified.

**Comment by mdbergmann** [comment]
Thanks
